language: cpp

env:
  global:
    - LINUX_DIST=bionic
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: true
      compiler: gcc
      addons:
       apt:
         packages:
           - python-yaml
           - doxygen
           - graphviz
script:
     - mkdir -p build
     - cd build
     - cmake .. -Dhueplusplus_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -Dhueplusplus_EXAMPLES=ON
     - make hueplusplus_examples hueplusplus_snippets
     - make coveragetest
     - cd ..
     - doxygen Doxyfile
     - touch doc/html/.nojekyll
